### ISSUE TITLE
Whether it can be used on non-framework projects ?

### ISSUE THREAD

**Issue by yansheng836** [Arman19941113/zoom-img#1]
It is a good tool, iIt looks very nice !

Whether it can be used on non-framework projects ?

**Comment by Arman19941113** [comment]
You mean project without npm? I can provide an browser version.

**Comment by Arman19941113** [comment]
> It is a good tool, iIt looks very nice !
> 
> Whether it can be used on non-framework projects ?

You mean project without npm? I can provide an browser version.

**Comment by yansheng836** [comment]
Thanks! I am looking forward to the version.:rose:
(I want to be able to use it in normal HTML pages just like jquery.)

**Comment by Arman19941113** [comment]
> Thanks! I am looking forward to the version.🌹
> (I want to be able to use it in normal HTML pages just like jquery.)

try this:
```html
<body>
  <img id="image" class="image" alt="" src="./girl.jpg" width="400" />
  <link rel="stylesheet" href="https://unpkg.com/handle-image-zoom/dist/index.css">
  <script src="https://unpkg.com/handle-image-zoom/dist/index.iife.js"></script>
  <script>
    const image = document.getElementById('image')
    image.addEventListener('click', handleImageZoom)
  </script>
</body>
```
